name: C++ Tests

on: [pull_request, push]

permissions:
  contents: read

jobs:
  cpp_maze_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Build and run test
      run: |
        XMAKE_ROOT=y xmake build maze_test
        XMAKE_ROOT=y xmake run maze_test